source = ~/.config/hypr/environment/env.conf
source = ~/.config/hypr/environment/monitors.conf
source = ~/.config/hypr/environment/execs.conf
source = ~/.config/hypr/environment/general.conf
source = ~/.config/hypr/environment/rules.conf
source = ~/.config/hypr/environment/theme.conf
source = ~/.config/hypr/environment/keybinds.conf
