-- ============================================================
-- THEME LOADER
-- ============================================================
-- Loads catppuccin color overrides from the theme system.
-- Colors file is generated by: theme generate <name>
-- Auto-reloads on FocusGained when the file changes.

local theme_file = vim.fn.expand("~/.config/themes/current/nvim-colors.lua")
local last_mtime = 0

local function load_theme_opts()
  local stat = vim.uv.fs_stat(theme_file)
  if not stat then
    return nil
  end
  local ok, opts = pcall(dofile, theme_file)
  if ok and type(opts) == "table" then
    return opts, stat.mtime.sec
  end
  return nil
end

local function is_light(hex)
  if not hex or #hex < 7 then
    return false
  end
  local r = tonumber(hex:sub(2, 3), 16) / 255
  local g = tonumber(hex:sub(4, 5), 16) / 255
  local b = tonumber(hex:sub(6, 7), 16) / 255
  return (0.2126 * r + 0.7152 * g + 0.0722 * b) > 0.5
end

local function apply_theme(opts)
  if not opts then
    return
  end
  local base = opts.color_overrides and opts.color_overrides.all and opts.color_overrides.all.base
  if base then
    vim.o.background = is_light(base) and "light" or "dark"
  end
  require("catppuccin").setup(opts)
  vim.cmd.colorscheme("catppuccin")
end

local function reload_if_changed()
  local stat = vim.uv.fs_stat(theme_file)
  if not stat then
    return
  end
  local mtime = stat.mtime.sec
  if mtime == last_mtime then
    return
  end
  last_mtime = mtime
  local opts = load_theme_opts()
  apply_theme(opts)
end

-- ---- Initial load ----

local theme_opts = load_theme_opts()
if theme_opts then
  local stat = vim.uv.fs_stat(theme_file)
  if stat then
    last_mtime = stat.mtime.sec
  end
end

-- reload on focus (covers theme changes while nvim is in background)
vim.api.nvim_create_autocmd("FocusGained", {
  callback = reload_if_changed,
})

return {
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "catppuccin",
    },
  },
  {
    "catppuccin/nvim",
    name = "catppuccin",
    opts = function()
      return theme_opts or {}
    end,
  },
}
