#################
### AUTOSTART ###
#################

# Portal and environment setup
exec-once = ~/.config/hypr/scripts/xdg-desktop-portal-reset.sh
exec-once = dbus-update-activation-environment --systemd --all
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Services
exec-once = systemctl --user start hyprpolkitagent
exec-once = hypridle
exec-once = hyprpm reload

# UI
exec-once = waybar
exec-once = hyprpaper && sleep 1 && hyprctl hyprpaper wallpaper ",/home/wiz/Documents/Pictures/Backgrounds/cat_leaves.png"
exec-once = ~/.config/hypr/scripts/set-cursor.sh

# Utilities
exec-once = clipse -listen
exec-once = udiskie
