# Toolkit Theme
env = GTK_THEME,catppuccin-mocha-lavender-standard+default
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_STYLE_OVERRIDE,kvantum
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1

# Cursor
env = XCURSOR_SIZE,24
env = XCURSOR_THEME,catppuccin-mocha-dark-cursors
env = HYPRCURSOR_SIZE,24
env = HYPRCURSOR_THEME,catppuccin-mocha-dark

##################
### APPEARANCE ###
##################

general {
  border_size = 1
  gaps_in = 5
  gaps_out = 10
  gaps_workspaces = 0
}

decoration {
  rounding = 3

  active_opacity = 0.90
  inactive_opacity = 0.75
  fullscreen_opacity = 1.0

  dim_inactive = true
  dim_strength = 0.15
  dim_special = 0.3
  dim_around = 0.4

  blur {
    enabled = true
    size = 8
    passes = 2
    ignore_opacity = false
    xray = false
    noise = 0.0
    contrast = 1.0
    brightness = 0.95
    vibrancy = 0.15
    vibrancy_darkness = 0.0
    popups = true
    popups_ignorealpha = 0.6
    special = true
  }

  shadow {
    enabled = true
    range = 20
    render_power = 3
    sharp = false
    ignore_window = true
    color = rgba(11111bee)
    color_inactive = rgba(11111b99)
    offset = 0 5
    scale = 1.0
  }
}

plugin {
  borders-plus-plus {
    add_borders = 1
    border_size_1 = 5
    border_size_2 = 5
    natural_rounding = yes
    # Make borders disappear instantly on workspace switch
    border_ignore_opacity = false
  }
}

##############
### COLORS ###
##############

source = ~/.config/hypr/appearance/colors.conf

general {
  col.active_border = rgba($lavenderAlphaFF)
  col.inactive_border = rgba($overlay0AlphaFF)
}

misc {
  background_color = rgba($baseAlphaFF)
}

plugin {
  borders-plus-plus {
    col.border_2 = rgba($lavenderAlphaFF)
    col.border_1 = rgba($baseAlphaFF)
  }
}

##################
### ANIMATIONS ###
##################

animations {
  enabled = true
}

source = ~/.config/hypr/appearance/animations.conf
