# Toolkit Theme
env = GTK_THEME,catppuccin-mocha-lavender-standard+default
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_STYLE_OVERRIDE,kvantum
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1

# Cursor - sourced from theme colors.conf
# env vars set in execs.conf after colors are loaded

##############
### COLORS ###
##############

source = ~/.config/hypr/appearance/colors.conf

##################
### APPEARANCE ###
##################

general {
  border_size = 1
  gaps_in = 5
  gaps_out = 10
  gaps_workspaces = 0
}

decoration {
  rounding = 3

  active_opacity = 0.90
  inactive_opacity = 0.75
  fullscreen_opacity = 1.0

  dim_inactive = true
  dim_strength = 0.15
  dim_special = 0.3
  dim_around = 0.4

  blur {
    enabled = true
    size = 8
    passes = 2
    ignore_opacity = false
    xray = false
    noise = 0.0
    contrast = 1.0
    brightness = 0.95
    vibrancy = 0.15
    vibrancy_darkness = 0.0
    popups = true
    popups_ignorealpha = 0.6
    special = true
  }

  shadow {
    enabled = true
    range = 20
    render_power = 3
    sharp = false
    ignore_window = true
    color = rgba($crustAlphaee)
    color_inactive = rgba($crustAlpha99)
    offset = 0 5
    scale = 1.0
  }
}

misc {
  background_color = rgba($baseAlphaFF)
}

plugin {
  borders-plus-plus {
    add_borders = 1
    border_size_1 = 5
    border_size_2 = 5
    natural_rounding = yes
    border_ignore_opacity = false
    col.border_1 = rgba($bpp1AlphaFF)
    col.border_2 = rgba($accentAlphaFF)
  }
}

##################
### ANIMATIONS ###
##################

animations {
  enabled = true
}

source = ~/.config/hypr/appearance/animations.conf
